### ISSUE TITLE
There is no built-in transformer

### ISSUE THREAD

**Issue by alizera** [best-flutter/transformer_page_view#28]
I cleaned the project, checked the lib version (0.1.6) but it can't find transformers, also I've checked the downloaded files inside `External  Libraries` and there is no transformer either.

![image](https://user-images.githubusercontent.com/50444607/88565140-6ee65400-d049-11ea-9d42-4cdb8f644376.png)

I suggest add `buildin_transformers.dart` file inside the lib.

**Comment by RNOVOSELOV** [comment]
@alizera  I have the same problem and don't see where are you add buildin_transformers.dart ?
